### ISSUE TITLE
Symfony Framework compliance

### ISSUE THREAD

**Issue by remilemonnier** [BedrockStreaming/RedisBundle#54]
The last PR merged on this project break the Symfony Framework compliance.

```
      -  "symfony/symfony": "~2.3||~3.0||~4.0",
      + "symfony/symfony": "~4.2",
```
This breaking change happens because of SF4 framework who has changed its dependencyInjection.

I saw a solution on another library:
https://github.com/schmittjoh/JMSSerializerBundle/pull/705/files#diff-850942b3ba24ab03a40aaa81b6152852

By checking if the getRootNode method exists or not we can provide a SF3/SF4/SF5 compatibility (I didn't check for SF2)
```
        if (method_exists($tb, 'getRootNode')) {
            $root = $tb->getRootNode()->children();
        } else {
            $root = $tb->root('jms_serializer')->children();
        }
```

I propose to do the Pull Request. We have SF3/SF4 project using your bundle and we need this change.

"Fun" fact, the last PR has been made by Stéphane for our project 😕

**Comment by pabedu** [comment]
Hello you @remilemonnier 👋 

Thanks in advance for the PR ;) 

We merged the same solution in another of our project https://github.com/M6Web/CassandraBundle/pull/44/files as well, so feel free to do the same then.

I'll slap @Stax whenever I see him ;)

**Comment by Oliboy50** [comment]
👋 FYI, you are still able to use a previous version of this bundle which supports Symfony 3.*

for example:

```shell
composer require m6web/redis-bundle:4.0.4
```

keep in mind that we won't be able to support old Symfony versions forever 🙂 
=> even Fabien Potencier said that bundles should be able to support only 2 major releases at the same time https://github.com/symfony/symfony/pull/34230#issuecomment-559084890

**Comment by remilemonnier** [comment]
Yep I know, but my app is not using directly this bundle.
We use an EntityBundle which has M6WebRedisBundle as a dependency.
Our EntityBundle is SF3/4 compliant.
Do you think that you will merge my PR?

**Comment by Oliboy50** [comment]
closing since [symfony 3](https://symfony.com/releases/3.4) is not officially maintained anymore
